# Reading data
Read the train.csv file as a pandas dataframe.

In [1]:
import pandas as pd
import numpy as np
from funciones import get_passenger, get_passengerId, porcentaje_sobrevivir

train = pd.read_csv('data/train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

5. Print all information about the oldest passenger.

In [8]:
print(train[train.PassengerId == 1]['Name'].values[0])
print(train.Name[train.PassengerId == 1].values[0])

print(train.PassengerId[train.Name == "Montvila, Rev. Juozas"].values[0])

Braund, Mr. Owen Harris
Braund, Mr. Owen Harris
887

In [2]:
print(f'The passenger with ID 42 is {get_passenger(train, 42)}')
print(f'The ID of passenger Montvila, Rev. Juozas is {get_passengerId(train, "Montvila, Rev. Juozas")}')

print(train[train.Age == train.Age.max()])

The passenger with ID 42 is Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)
The ID of passenger Montvila, Rev. Juozas is 887
     PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson

      Sex   Age  SibSp  Parch Ticket  Fare Cabin Embarked
630  male  80.0      0      0  27042  30.0   A23        S

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [15]:
print(train.get(['Pclass','Fare', 'Embarked'])[:100])

    Pclass     Fare Embarked
0        3   7.2500        S
1        1  71.2833        C
2        3   7.9250        S
3        1  53.1000        S
4        3   8.0500        S
..     ...      ...      ...
95       3   8.0500        S
96       1  34.6542        C
97       1  63.3583        C
98       2  23.0000        S
99       2  26.0000        S

[100 rows x 3 columns]

In [3]:
port_fares = train.get(['Pclass', 'Fare', 'Embarked'])[:100]
port_fares.to_csv('data/port_fares.csv')

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [22]:
print(train[(train.Age > 60) & (train.Survived == 1)])
print(train[(train.Age > 60) & (train.Survived == 1)].shape[0])
print(train[(train.Age > 60) & (train.Survived == 1)].shape[0]/train[(train.Age > 60)].shape[0] * 100)

     PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia
483          484         1       3                     Turkula, Mrs. (Hedwig)
570          571         1       2                         Harris, Mr. George
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)

        Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked
275  female  63.0      1      0        13502  77.9583    D7        S
483  female  63.0      0      0         4134   9.5875   NaN        S
570    male  62.0      0      0  S.W./PP 752  10.5000   NaN        S
630    male  80.0      0      0        27042  30.0000   A23        S
829  female  62.0      0      0       113572  80.0000   B28      NaN
5
22.727272727272727

In [8]:
print('Informacion de supervivientes')
print(train[(train.Age > 60) & (train.Survived == 1)])
print('')
print('Cuantos sobrevivieron')
print(train[(train.Age > 60) & (train.Survived == 1)].shape[0])
print('')
print('Porcentaje de supervivencia')
print(train[(train.Age > 60) & (train.Survived == 1)].shape[0] / train[(train.Age > 60)].shape[0] * 100, '%')

Informacion de supervivientes
     PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia
483          484         1       3                     Turkula, Mrs. (Hedwig)
570          571         1       2                         Harris, Mr. George
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)

        Sex   Age  SibSp  Parch       Ticket     Fare Cabin Embarked
275  female  63.0      1      0        13502  77.9583    D7        S
483  female  63.0      0      0         4134   9.5875   NaN        S
570    male  62.0      0      0  S.W./PP 752  10.5000   NaN        S
630    male  80.0      0      0        27042  30.0000   A23        S
829  female  62.0      0      0       113572  80.0000   B28      NaN

Cuantos sobrevivieron
5

Porcentaje de supervivencia
22.727272727272727 %

In [9]:
train.groupby(['Survived', 'Sex'])['Age'].median()

Survived  Sex
0         female    24.5
          male      29.0
1         female    28.0
          male      28.0
Name: Age, dtype: float64

In [44]:
train['Mayor_60'] = train.Survived[train['Age'] > 60]
train['Menor_60'] = train.Survived[train['Age'] <= 60]
a = train.groupby(['Mayor_60', 'Survived', 'Sex'])['Survived'].count()
b = train.groupby(['Menor_60', 'Survived', 'Sex'])['Survived'].count()
result = pd.concat([a, b], keys=['Mayor_60', 'Menor_60'])
print(result)

print(a)
print(b)
pd.merge(a,b,how='outer',on=['Mayor_60','Menor_60'])

               Survived  Sex
Mayor_60  0.0  0         male       17
          1.0  1         female      3
                         male        2
Menor_60  0.0  0         female     64
                         male      343
          1.0  1         female    194
                         male       91
Name: Survived, dtype: int64
Mayor_60  Survived  Sex
0.0       0         male      17
1.0       1         female     3
                    male       2
Name: Survived, dtype: int64
Menor_60  Survived  Sex
0.0       0         female     64
                    male      343
1.0       1         female    194
                    male       91
Name: Survived, dtype: int64

KeyError: 'Mayor_60'

In [33]:
train.iloc[0:10,1:4]

   Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry
5         0       3                                   Moran, Mr. James
6         0       1                            McCarthy, Mr. Timothy J
7         0       3                     Palsson, Master. Gosta Leonard
8         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9         1       2                Nasser, Mrs. Nicholas (Adele Achem)

# Women and children first?
10. Find out if women and children were more likely to survive.

In [5]:
kids = train[train.Age < 18]
women = train[(train.Age >= 18) & (train.Sex == 'female')]
men = train[(train.Age >= 18) & (train.Sex == 'male')]

print("% de niños que sobrevivieron:", kids[kids.Survived == 1].shape[0] / kids.shape[0] * 100,'%')
print("% de mujeres que sobrevivieron:",women[women.Survived == 1].shape[0] / women.shape[0] * 100,'%')
print("% de hombres que sobrevivieron:",men[men.Survived == 1].shape[0] / men.shape[0] * 100,'%')

% de niños que sobrevivieron: 53.98230088495575 %
% de mujeres que sobrevivieron: 77.18446601941747 %
% de hombres que sobrevivieron: 17.72151898734177 %

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

In [6]:
porcentaje_sobrevivir(train, 'Survived')

'38.38383838383838 %'

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

In [7]:
print(train.Age.median())

print(train.Embarked.value_counts())

28.0
S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [ ]:
# Hipotesis 1: Ratio de supervivencia por clase de ticket

print("Esta es la hipótesis 1: Mientras más alta sea la clase de ticket, mayor será la probabilidad de supervivencia")
survival_rate_by_class = train.groupby('Pclass')['Survived'].mean() * 100
print("Ratio de supervivencia por clase de ticket:")
print(survival_rate_by_class)

print("Se puede observar que la hipótesis es cierta")
print("Las personas con tickets de clase 1 tienen una probabilidad de supervivencia mucho mayor que las personas con tickets de clase 3 \n")

# Hipotesis 2: Ratio de supervivencia por género
print("Esta es la hipótesis 2: Las mujeres tienen mayor probabilidad de supervivencia que los hombres")
survival_rate_by_gender = train.groupby('Sex')['Survived'].mean() * 100
print("\nRatio de supervivencia por género:")
print(survival_rate_by_gender)

print("Se comprueba que la hipótesis es cierta")
print("Se puede observar que las mujeres tienen una probabilidad de supervivencia mucho mayor que los hombres")

Esta es la hipótesis 1: Mientras más alta sea la clase de ticket, mayor será la probabilidad de supervivencia
Ratio de supervivencia por clase de ticket:
Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64
Se puede observar que la hipótesis es cierta
Las personas con tickets de clase 1 tienen una probabilidad de supervivencia mucho mayor que las personas con tickets de clase 3

Esta es la hipótesis 2: Las mujeres tienen mayor probabilidad de supervivencia que los hombres

Ratio de supervivencia por género:
Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64
Se comprueba que la hipótesis es cierta
Se puede observar que las mujeres tienen una probabilidad de supervivencia mucho mayor que los hombres

In [ ]:
import time
import numpy as np

start = time.time()

total = 0
for i in np.arange(1000000):
    total += i 
print(total)
end = time.time()
print(end - start)

499999500000
0.22881484031677246

In [ ]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()   
print(end - start)

49999995000000
0.06715250015258789